### PR TITLE
Update runtime version to 23.08

### LINKED ISSUE #15: Needs update to 23.08 and vkBasalt version 0.3.2.10
Steam just updated to runtime 23.08 this being still on 22.08 means it isnt working anymore unless you downgrade steam. vkBasalt also had an update at the beginning of july which while really just a GCC fix im not sure there is a reason not to update this also.

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.vkBasalt/issues/15

### CODE REVIEW

**Comment by orowith2os** [comment]
bot, build

**Comment by orowith2os** [comment]
Needs spirv-headers.

**Comment by Eckoa** [comment]
is this still building against  Version 0.3.2.9? Version 0.3.2.10 fixes build failures related to using GCC12 and im not sure what the updates for building with flatpak may be for 23.08

EDIT: just checked the commits is the latest nevermind

**Comment by orowith2os** [comment]
bot, build

**Comment by orowith2os** [comment]
Bingo!

**Pull request merged**
